# Generated by Django 5.0.1 on 2024-02-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_gallary', '0004_team_academic_background_team_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
