# Generated by Django 5.0.1 on 2024-02-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_gallary', '0005_remove_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
